name: Sync channels

on: 
  schedule:
    - cron: "31 21 * * *" # daily
  workflow_dispatch: # on button click
  push:
    branches:
      - develop
jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch:
        - nixos-22.11
        - nixpkgs-unstable
        - nixos-unstable
        - master

    steps:
    - uses: actions/checkout@v3
      with:
        # Flakes don't like shallow clones
        fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        install_url: https://releases.nixos.org/nix/nix-2.9.1/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - run: ./sync.sh ${{ matrix.branch }}

